version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "8000:9000"
    environment:
      APP_ENV: production
      APP_DEBUG: false
      APP_KEY: base64:GENERATE_YOUR_APP_KEY_HERE
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: stegdb
      DB_USERNAME: stegdb_user
      DB_PASSWORD: Q4WE0BImAiFDo5ijMhZIdwRsfjIRSBcP

  db:
    image: postgres:14
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: stegdb_user
      POSTGRES_PASSWORD: Q4WE0BImAiFDo5ijMhZIdwRsfjIRSBcP
      POSTGRES_DB: stegdb
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
