services:
  - type: web
    name: laravel-app
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:GENERATE_YOUR_APP_KEY_HERE
      - key: APP_DEBUG
        value: "false"
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-cu55e1bv2p9s73a0ah80-a.oregon-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: stegdb
      - key: DB_USERNAME
        value: stegdb_user
      - key: DB_PASSWORD
        value: Q4WE0BImAiFDo5ijMhZIdwRsfjIRSBcP
